version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

tasks:
  build:
    desc: Build shhh binary for current platform
    cmds:
      - go build -ldflags "-s -w -X main.version={{.VERSION}}" -o shhh ./cmd/shhh

  build-windows:
    desc: Cross-compile for Windows
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -ldflags "-s -w -X main.version={{.VERSION}}" -o shhh.exe ./cmd/shhh

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test-verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test ./... -v

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f shhh shhh.exe

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
